/**
 * appState.js
 * Shared mutable state object for legacy API modules (oba.js, arrivals.js, static-data.js).
 * After mutations that should be reflected in React, call syncToStore() from useAppStore.js.
 */

import { DEFAULT_SYSTEM_ID } from '../config'

export const appState = {
  fetchedAt: '',
  error: '',
  activeSystemId: DEFAULT_SYSTEM_ID,
  activeTab: 'map',
  activeLineId: '',
  compactLayout: false,
  theme: 'dark',
  language: 'en',
  currentDialogStationId: '',
  systemsById: new Map(),
  layoutsBySystem: new Map(),
  lines: [],
  layouts: new Map(),
  vehiclesByLine: new Map(),
  directionFilterByLine: new Map(),
  rawVehicles: [],
  arrivalsCache: new Map(),
  activeDialogRequest: 0,
  isSyncingFromUrl: false,
  currentDialogStation: null,
  dialogOpenerElement: null,
  dialogRefreshTimer: 0,
  liveRefreshTimer: 0,
  liveMetaTimer: 0,
  dialogDisplayMode: false,
  dialogDisplayDirection: 'both',
  dialogDisplayAutoPhase: 'nb',
  dialogDisplayDirectionTimer: 0,
  dialogDisplayDirectionAnimationTimer: 0,
  dialogDisplayAnimatingDirection: '',
  dialogDisplayTimer: 0,
  dialogDisplayIndexes: { nb: 0, sb: 0 },
  insightsTickerIndex: 0,
  insightsTickerTimer: 0,
  currentTrainId: '',
  alerts: [],
  systemSnapshots: new Map(),
  vehicleGhosts: new Map(),
  stationSearchQuery: '',
  stationSearchResults: [],
  highlightedStationSearchIndex: 0,
  activeDialogType: '',
  currentInsightsDetailType: '',
  currentInsightsLineId: '',
  dialogAbortController: null,
  nearbyStations: [],
  highlightedNearbyStationIndex: 0,
  geolocationStatus: '',
  geolocationError: '',
  isLocating: false,
  userLocation: null,
  favoriteArrivals: new Map(),
  favoriteArrivalsRequestId: 0,
  favoriteArrivalsRefreshPromise: null,
}
