export function getAppElements() {
  return {
    boardElement: document.querySelector('#board'),
    screenKickerElement: document.querySelector('#screen-kicker'),
    screenTitleElement: document.querySelector('#screen-title'),
    systemBarElement: document.querySelector('#system-bar'),
    viewBarElement: document.querySelector('#view-bar'),
    tabButtons: [...document.querySelectorAll('.tab-button')],
    stationSearchToggleButton: document.querySelector('#station-search-toggle'),
    languageToggleButton: document.querySelector('#language-toggle'),
    themeToggleButton: document.querySelector('#theme-toggle'),
    statusPillElement: document.querySelector('#status-pill'),
    currentTimeElement: document.querySelector('#current-time'),
    updatedAtElement: document.querySelector('#updated-at'),
    aboutToggleButton: document.querySelector('#about-toggle'),
    toastRegionElement: document.querySelector('#toast-region'),
    stationSearchDialog: document.querySelector('#station-search-dialog'),
    stationSearchTitleElement: document.querySelector('#station-search-title'),
    stationSearchSummaryElement: document.querySelector('#station-search-summary'),
    stationSearchInput: document.querySelector('#station-search-input'),
    stationSearchMetaElement: document.querySelector('#station-search-meta'),
    stationSearchResultsElement: document.querySelector('#station-search-results'),
    stationSearchCloseButton: document.querySelector('#station-search-close'),
    stationLocationButton: document.querySelector('#station-location-button'),
    stationLocationStatusElement: document.querySelector('#station-location-status'),
    aboutDialog: document.querySelector('#about-dialog'),
    aboutDialogTitle: document.querySelector('#about-dialog-title'),
    aboutDialogSummary: document.querySelector('#about-dialog-summary'),
    aboutDialogBody: document.querySelector('#about-dialog-body'),
    aboutDialogCloseButton: document.querySelector('#about-dialog-close'),
    stationDialogCloseButton: document.querySelector('#station-dialog-close'),
    dialogFavoriteButton: document.querySelector('#dialog-favorite'),
    rideModeChip: document.querySelector('#ride-mode-chip'),
    rideModeChipLabel: document.querySelector('#ride-mode-chip-label'),
  }
}
