export const DATA_URL = './pulse-data.json'
export const SYSTEM_DATA_URL = (systemId) => `./pulse-data-${systemId}.json`
export const OBA_BASE_URL = 'https://api.pugetsound.onebusaway.org/api/where'
export const OBA_KEY = (import.meta.env.VITE_OBA_KEY || 'TEST').trim() || 'TEST'
export const IS_PUBLIC_TEST_KEY = OBA_KEY === 'TEST'
export const ARRIVALS_CACHE_TTL_MS = IS_PUBLIC_TEST_KEY ? 60_000 : 20_000
export const OBA_CACHE_TTL_MS = IS_PUBLIC_TEST_KEY ? 60_000 : 20_000
export const OBA_MAX_RETRIES = 3
export const OBA_COOLDOWN_BASE_MS = IS_PUBLIC_TEST_KEY ? 20_000 : 5_000
export const OBA_COOLDOWN_MAX_MS = IS_PUBLIC_TEST_KEY ? 120_000 : 30_000
export const OBA_ARRIVALS_CONCURRENCY = IS_PUBLIC_TEST_KEY ? 1 : 3
export const COMPACT_LAYOUT_BREAKPOINT = 1100
export const VEHICLE_REFRESH_INTERVAL_MS = IS_PUBLIC_TEST_KEY ? 45_000 : 15_000
export const DIALOG_REFRESH_INTERVAL_MS = IS_PUBLIC_TEST_KEY ? 90_000 : 30_000
export const DIALOG_DISPLAY_SCROLL_INTERVAL_MS = 4_000
export const DIALOG_DISPLAY_DIRECTION_ROTATE_MS = 15_000
export const DIALOG_DISPLAY_DIRECTION_ANIMATION_MS = 520
export const GHOST_HISTORY_LIMIT = 6
export const GHOST_MAX_AGE_MS = 4 * 60_000
export const THEME_STORAGE_KEY = 'link-pulse-theme'
export const LANGUAGE_STORAGE_KEY = 'link-pulse-language'
export const FAVORITES_STORAGE_KEY = 'link-pulse-favorite-stations'
export const DEFAULT_SYSTEM_ID = 'link'

export const SYSTEM_META = {
  link: {
    id: 'link',
    agencyId: '40',
    label: 'Link',
    kicker: 'SEATTLE LIGHT RAIL',
    title: 'LINK PULSE',
    vehicleLabel: 'Train',
    vehicleLabelPlural: 'Trains',
  },
  rapidride: {
    id: 'rapidride',
    agencyId: '1',
    label: 'RapidRide',
    kicker: 'KING COUNTY METRO',
    title: 'RAPIDRIDE PULSE',
    vehicleLabel: 'Bus',
    vehicleLabelPlural: 'Buses',
  },
  swift: {
    id: 'swift',
    agencyId: '29',
    label: 'Swift',
    kicker: 'COMMUNITY TRANSIT',
    title: 'SWIFT PULSE',
    vehicleLabel: 'Bus',
    vehicleLabelPlural: 'Buses',
  },
}

export const UI_COPY = {
  en: {
    languageToggle: '中文',
    languageToggleAria: 'Switch to Chinese',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeToggleAria: 'Toggle color theme',
    transitSystems: 'Transit systems',
    boardViews: 'Board views',
    openStationSearch: 'Station search',
    stationFavorites: 'Favorites',
    favoriteStation: 'Save station',
    unfavoriteStation: 'Saved station',
    favoritesEmpty: 'Save stations for one-tap access here.',
    favoritesCount: (count) => `${count} favorite${count === 1 ? '' : 's'}`,
    addedFavorite: (name) => `Saved ${name}`,
    removedFavorite: (name) => `Removed ${name}`,
    stationSearchPlaceholder: 'Search stations, lines, or systems',
    stationSearchHint: 'Jump straight to any station across loaded systems.',
    useMyLocation: 'Use my location',
    locationFindingButton: 'Locating…',
    locationFinding: 'Requesting your location…',
    locationFoundNearby: (count) => `Showing ${count} nearest station${count === 1 ? '' : 's'}`,
    locationNoNearby: 'No nearby stations found in loaded data.',
    locationPermissionDenied: 'Location permission was denied.',
    locationUnavailable: 'Current location is unavailable.',
    locationTimedOut: 'Location request timed out.',
    locationFailed: 'Could not get your location.',
    locationUnsupported: 'This browser does not support geolocation.',
    nearbyStationsHint: 'Use your location to find the nearest stations.',
    nearbyStationsFound: (count) => `${count} nearby station${count === 1 ? '' : 's'}`,
    nearbyStationBadge: 'Nearby',
    searchShortcut: 'Press / to search',
    noStationSearchResults: 'No stations matched that search.',
    stationSearchResults: (count) => `${count} station${count === 1 ? '' : 's'} found`,
    tabMap: 'Map',
    tabInsights: 'Insights',
    statusSync: 'SYNC',
    statusHold: 'HOLD',
    statusFail: 'FAIL',
    nowPrefix: 'Now',
    waitingSnapshot: 'Waiting for snapshot',
    updatedNow: 'Updated now',
    updatedSecondsAgo: (seconds) => `Updated ${seconds}s ago`,
    updatedMinutesAgo: (minutes) => `Updated ${minutes}m ago`,
    station: 'Station',
    serviceSummary: 'Service summary',
    boardDirectionView: 'Board direction view',
    both: 'Both',
    auto: 'Auto',
    board: 'Board',
    exit: 'Exit',
    northbound: 'Northbound (▲)',
    southbound: 'Southbound (▼)',
    train: 'Train',
    currentMovement: 'Current movement',
    closeTrainDialog: 'Close train dialog',
    serviceAlert: 'Service Alert',
    transitAdvisory: 'Transit advisory',
    closeAlertDialog: 'Close alert dialog',
    readOfficialAlert: 'Read official alert',
    arriving: 'Arriving',
    todayServiceUnavailable: 'Today service hours unavailable',
    todayServiceSpan: (start, end) => `Today ${start} - ${end}`,
    lastTrip: (time) => `Last trip ${time}`,
    endsIn: (duration) => `Ends in ${duration}`,
    firstTrip: (time) => `First trip ${time}`,
    startsIn: (duration) => `Starts in ${duration}`,
    serviceEnded: (time) => `Service ended ${time}`,
    nextStart: (time) => `Next start ${time}`,
    noNextServiceLoaded: 'No next service loaded',
    ended: 'Ended',
    nextFirstTrip: (time) => `Next first trip ${time}`,
    noServiceRemainingToday: 'No service remaining today',
    serviceHoursUnavailable: 'Service hours unavailable',
    staticScheduleMissing: 'Static schedule data missing for this date',
    unavailable: 'Unavailable',
    serviceSummaryUnavailable: 'Service summary unavailable',
    alertsWord: (count) => `alert${count === 1 ? '' : 's'}`,
    scheduled: 'Scheduled',
    onTime: 'On Time',
    unknown: 'Unknown',
    arrivingStatus: 'ARRIVING',
    delayedStatus: 'DELAYED',
    enRoute: 'EN ROUTE',
    arrivingNow: 'Arriving now',
    arrivingIn: (time) => `Arriving in ${time}`,
    nextStopIn: (time) => `Next stop in ${time}`,
    active: 'Active',
    noLiveVehicles: (label) => `No live ${label}`,
    liveCount: (count, label) => `${count} live ${label}`,
    inServiceCount: (count, label) => `${count} ${label} in service`,
    activeVehicles: (label) => `Active ${label}`,
    previous: 'Previous',
    now: 'Now',
    next: 'Next',
    direction: 'Direction',
    terminal: 'Terminal',
    etaToTerminal: 'ETA to Terminal',
    upcomingStops: 'Upcoming stops',
    liveEtaNow: 'Live ETA now',
    nextStop: 'Next stop',
    upcoming: 'Upcoming',
    noDownstreamEta: 'No downstream ETA available for this train right now.',
    terminalFallback: 'Terminal',
    loadingArrivals: 'Loading arrivals...',
    noUpcomingVehicles: (label) => `No upcoming ${label}`,
    noAdditionalVehicles: (label) => `No additional ${label}`,
    stopAway: (count) => `${count} stop${count === 1 ? '' : 's'} away`,
    toDestination: (name) => `To ${name}`,
    activeAlerts: (count) => `${count} active ${count === 1 ? 'alert' : 'alerts'}`,
    noActiveAlerts: 'No active alerts.',
    noAdditionalAlertDetails: 'No additional alert details available.',
    affectedLineAlerts: (lineName, count) => `${lineName} Alerts`,
    realtimeOffline: 'Realtime offline',
    realtimeRequestFailed: 'Realtime request failed. Using last successful snapshot.',
    stationRequestFailed: 'Station arrivals request failed.',
    startupRequestFailed: 'Initial data request failed.',
  },
  'zh-CN': {
    languageToggle: 'EN',
    languageToggleAria: '切换到英文',
    themeLight: '浅色',
    themeDark: '深色',
    themeToggleAria: '切换主题',
    transitSystems: '交通系统',
    boardViews: '视图切换',
    openStationSearch: '站点搜索',
    stationFavorites: '收藏',
    favoriteStation: '收藏站点',
    unfavoriteStation: '已收藏站点',
    favoritesEmpty: '收藏常用站点后，可在这里一键打开。',
    favoritesCount: (count) => `${count} 个收藏站点`,
    addedFavorite: (name) => `已收藏 ${name}`,
    removedFavorite: (name) => `已移除 ${name}`,
    stationSearchPlaceholder: '搜索站点、线路或系统',
    stationSearchHint: '可直接跳转到任意已加载系统中的站点。',
    useMyLocation: '用我的位置',
    locationFindingButton: '定位中…',
    locationFinding: '正在请求你的位置…',
    locationFoundNearby: (count) => `显示最近的 ${count} 个站点`,
    locationNoNearby: '在当前已加载数据里没有找到附近站点。',
    locationPermissionDenied: '定位权限被拒绝。',
    locationUnavailable: '当前位置暂时不可用。',
    locationTimedOut: '定位请求超时。',
    locationFailed: '无法获取当前位置。',
    locationUnsupported: '当前浏览器不支持定位。',
    nearbyStationsHint: '点击“用我的位置”即可查找最近站点。',
    nearbyStationsFound: (count) => `${count} 个附近站点`,
    nearbyStationBadge: '附近',
    searchShortcut: '按 / 键搜索',
    noStationSearchResults: '没有匹配的站点。',
    stationSearchResults: (count) => `找到 ${count} 个站点`,
    tabMap: '地图',
    tabInsights: '洞察',
    statusSync: '同步',
    statusHold: '保留',
    statusFail: '失败',
    nowPrefix: '当前',
    waitingSnapshot: '等待快照',
    updatedNow: '刚刚更新',
    updatedSecondsAgo: (seconds) => `${seconds} 秒前更新`,
    updatedMinutesAgo: (minutes) => `${minutes} 分钟前更新`,
    station: '站点',
    serviceSummary: '服务摘要',
    boardDirectionView: '到站屏方向视图',
    both: '双向',
    auto: '自动',
    board: '到站屏',
    exit: '退出',
    northbound: '北向 (▲)',
    southbound: '南向 (▼)',
    train: '列车',
    currentMovement: '当前位置',
    closeTrainDialog: '关闭列车详情',
    serviceAlert: '服务告警',
    transitAdvisory: '交通提示',
    closeAlertDialog: '关闭告警详情',
    readOfficialAlert: '查看官方告警',
    arriving: '即将到站',
    todayServiceUnavailable: '今日运营时间不可用',
    todayServiceSpan: (start, end) => `今日 ${start} - ${end}`,
    lastTrip: (time) => `末班 ${time}`,
    endsIn: (duration) => `${duration} 后结束`,
    firstTrip: (time) => `首班 ${time}`,
    startsIn: (duration) => `${duration} 后开始`,
    serviceEnded: (time) => `已于 ${time} 收班`,
    nextStart: (time) => `下次首班 ${time}`,
    noNextServiceLoaded: '暂无下一班服务数据',
    ended: '已结束',
    nextFirstTrip: (time) => `下一次首班 ${time}`,
    noServiceRemainingToday: '今日无剩余服务',
    serviceHoursUnavailable: '运营时间不可用',
    staticScheduleMissing: '当前日期缺少静态时刻表数据',
    unavailable: '不可用',
    serviceSummaryUnavailable: '暂无服务摘要',
    alertsWord: () => '告警',
    scheduled: '按时刻表',
    onTime: '准点',
    unknown: '未知',
    arrivingStatus: '即将到站',
    delayedStatus: '晚点',
    enRoute: '运行中',
    arrivingNow: '正在进站',
    arrivingIn: (time) => `${time} 后到站`,
    nextStopIn: (time) => `下一站 ${time}`,
    active: '运营中',
    noLiveVehicles: (label) => `暂无实时${label}`,
    liveCount: (count, label) => `${count} 辆实时${label}`,
    inServiceCount: (count, label) => `${count} 辆${label}运营中`,
    activeVehicles: (label) => `${label}列表`,
    previous: '上一站',
    now: '当前',
    next: '下一站',
    direction: '方向',
    terminal: '终点',
    etaToTerminal: '到终点 ETA',
    upcomingStops: '后续站点',
    liveEtaNow: '实时 ETA',
    nextStop: '下一站',
    upcoming: '后续',
    noDownstreamEta: '当前暂无这趟列车后续站点 ETA。',
    terminalFallback: '终点',
    loadingArrivals: '正在加载到站信息...',
    noUpcomingVehicles: (label) => `暂无即将到站的${label}`,
    noAdditionalVehicles: (label) => `暂无更多${label}`,
    stopAway: (count) => `还有 ${count} 站`,
    toDestination: (name) => `开往 ${name}`,
    activeAlerts: (count) => `${count} 条生效告警`,
    noActiveAlerts: '当前没有生效告警。',
    noAdditionalAlertDetails: '暂无更多告警详情。',
    affectedLineAlerts: (lineName) => `${lineName} 告警`,
    realtimeOffline: '实时数据离线',
    realtimeRequestFailed: '实时请求失败，正在使用最近一次成功快照。',
    stationRequestFailed: '站点到站请求失败。',
    startupRequestFailed: '初始数据请求失败。',
  },
}
