export const UI_COPY = {
  en: {
    languageToggle: '中文',
    languageToggleAria: 'Switch to Chinese',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeToggleAria: 'Toggle color theme',
    transitSystems: 'Transit systems',
    boardViews: 'Board views',
    openStationSearch: 'Station search',
    openAbout: 'About',

    stationSearchPlaceholder: 'Search stations, lines, or systems',
    stationSearchHint: 'Jump straight to any station across loaded systems.',
    useMyLocation: 'Use my location',
    locationFindingButton: 'Locating…',
    locationFinding: 'Requesting your location…',
    locationFoundNearby: (count) => `Showing ${count} nearest station${count === 1 ? '' : 's'}`,
    locationNoNearby: 'No nearby stations found in loaded data.',
    locationPermissionDenied: 'Location permission was denied.',
    locationUnavailable: 'Current location is unavailable.',
    locationTimedOut: 'Location request timed out.',
    locationFailed: 'Could not get your location.',
    locationUnsupported: 'This browser does not support geolocation.',
    nearbyStationsHint: 'Use your location to find the nearest stations.',
    nearbyStationsFound: (count) => `${count} nearby station${count === 1 ? '' : 's'}`,
    nearbyStationBadge: 'Nearby',
    realtimeBadge: 'LIVE',
    scheduleBadge: 'SCHED',
    searchShortcut: 'Press / to search',
    searchKeyboardHint: '↑↓ navigate · Enter select',
    recentSearches: 'Recent',
    recentlyViewed: 'Recently Viewed',
    noStationSearchResults: 'No stations matched that search.',
    stationSearchResults: (count) => `${count} station${count === 1 ? '' : 's'} found`,
    tabMap: 'Map',
    tabFavorites: 'Favorites',
    tabInsights: 'Insights',
    statusSync: 'SYNC',
    statusHold: 'HOLD',
    statusFail: 'FAIL',
    waitingSnapshot: 'Waiting for snapshot',
    updatedNow: 'Updated now',
    updatedSecondsAgo: (seconds) => `Updated ${seconds}s ago`,
    updatedMinutesAgo: (minutes) => `Updated ${minutes}m ago`,
    station: 'Station',
    serviceSummary: 'Service summary',
    boardDirectionView: 'Board direction view',
    both: 'Both',
    directionUp: '上行',
    directionDown: '下行',
    board: 'Board',
    exit: 'Exit',
    northbound: 'Northbound (▲)',
    southbound: 'Southbound (▼)',
    train: 'Train',
    currentMovement: 'Current movement',
    closeTrainDialog: 'Close train dialog',
    serviceAlert: 'Service Alert',
    transitAdvisory: 'Transit advisory',
    closeAlertDialog: 'Close alert dialog',
    readOfficialAlert: 'Read official alert',
    aboutTitle: 'About Link Pulse',
    aboutSummary: 'Privacy, support, and release info',
    closeAboutDialog: 'Close about dialog',
    aboutProductTitle: 'App',
    aboutProductBody: (version) => `Link Pulse ${version} is a mobile live board for Link, RapidRide, and Swift.`,
    aboutPrivacyTitle: 'Privacy',
    aboutPrivacyBody: 'Location is only requested when you choose nearby station search. Favorites, recent stations, theme, and language are stored on your device. The app runs without an account.',
    aboutPrivacyLink: 'Open privacy policy',
    aboutSupportTitle: 'Support',
    aboutSupportBody: 'Questions, bug reports, and feedback can be sent through the project support page.',
    aboutSupportLink: 'Get support',
    aboutSourceTitle: 'Source',
    aboutSourceBody: (bundleId) => `Bundle ID ${bundleId}`,
    aboutSourceLink: 'View source',
    shareArrivals: 'Share',
    shareArrivalsAria: 'Share arrival times',
    shareSuccess: 'Arrivals shared!',
    shareCopied: 'Arrivals copied to clipboard',
    shareFailed: 'Could not share arrivals',
    addFavorite: 'Add to favorites',
    removeFavorite: 'Remove from favorites',
    moveUp: 'Move up',
    moveDown: 'Move down',
    favoriteAdded: 'Added to favorites',
    favoriteRemoved: 'Removed from favorites',
    noFavorites: 'No favorite stations yet.',
    favoritesHint: 'Save stations you use often for quick access.',
    favoritesTitle: 'Favorite Stations',
    favoritesLiveHint: 'Favorites now show the next live arrivals in each direction.',
    favoritesArrivalsLoading: 'Loading live arrivals…',
    favoritesArrivalsUnavailable: 'Live arrivals are temporarily unavailable.',
    favoritesStationMissing: 'This station is no longer available in the loaded dataset.',
    favoritesNoUpcoming: (label) => `No upcoming ${label} in the next hour`,
    arriving: 'Arriving',
    todayServiceUnavailable: 'Today service hours unavailable',
    todayServiceSpan: (start, end) => `Today ${start} - ${end}`,
    lastTrip: (time) => `Last trip ${time}`,
    endsIn: (duration) => `Ends in ${duration}`,
    firstTrip: (time) => `First trip ${time}`,
    startsIn: (duration) => `Starts in ${duration}`,
    serviceEnded: (time) => `Service ended ${time}`,
    nextStart: (time) => `Next start ${time}`,
    noNextServiceLoaded: 'No next service loaded',
    ended: 'Ended',
    nextFirstTrip: (time) => `Next first trip ${time}`,
    noServiceRemainingToday: 'No service remaining today',
    serviceHoursUnavailable: 'Service hours unavailable',
    staticScheduleMissing: 'Static schedule data missing for this date',
    unavailable: 'Unavailable',
    serviceSummaryUnavailable: 'Service summary unavailable',
    alertsWord: (count) => `alert${count === 1 ? '' : 's'}`,
    scheduled: 'Scheduled',
    onTime: 'On Time',
    unknown: 'Unknown',
    lateMinutes: (min) => `+${min} min late`,
    earlyMinutes: (min) => `${min} min early`,
    onTimeStatus: 'ON TIME',
    arrivalMinSec: (m, s) => `${m}m ${s}s`,
    arrivalSec: (s) => `${s}s`,
    durationHoursMinutes: (h, m) => `${h}h ${m}m`,
    durationHours: (h) => `${h}h`,
    durationMinutes: (m) => `${m}m`,
    nextDaySuffix: (offset) => ` (+${offset}d)`,
    arrivingStatus: 'ARRIVING',
    delayedStatus: 'DELAYED',
    enRoute: 'EN ROUTE',
    arrivingNow: 'Arriving now',
    arrivingIn: (time) => `Arriving in ${time}`,
    nextStopIn: (time) => `Next stop in ${time}`,
    active: 'Active',
    noLiveVehicles: (label) => `No live ${label}`,
    liveCount: (count, label) => `${count} live ${label}`,
    inServiceCount: (count, label) => `${count} ${label} in service`,
    activeVehicles: (label) => `Active ${label}`,
    previous: 'Previous',
    now: 'Now',
    next: 'Next',
    direction: 'Direction',
    terminal: 'Terminal',
    etaToTerminal: 'ETA to Terminal',
    upcomingStops: 'Upcoming stops',
    liveEtaNow: 'Live ETA now',
    currentLocation: 'Location',
    nextStop: 'Next stop',
    progress: 'Progress',
    lineProgress: (pct) => `${pct}%`,
    directionAll: 'All',
    filterByDirection: 'Filter by direction',
    headwayGap: (min) => `${min} min gap`,
    headwayGapLabel: (min) => `${min} min`,
    upcoming: 'Upcoming',
    noDownstreamEta: 'No downstream ETA available for this train right now.',
    terminalFallback: 'Terminal',
    loadingArrivals: 'Loading arrivals...',
    noUpcomingVehicles: (label) => `No upcoming ${label}`,
    noAdditionalVehicles: (label) => `No additional ${label}`,
    stopAway: (count) => `${count} stop${count === 1 ? '' : 's'} away`,
    toDestination: (name) => `To ${name}`,
    activeAlerts: (count) => `${count} active ${count === 1 ? 'alert' : 'alerts'}`,
    noActiveAlerts: 'No active alerts.',
    noAdditionalAlertDetails: 'No additional alert details available.',
    affectedLineAlerts: (lineName, count) => `${lineName} Alerts`,
    realtimeOffline: 'Realtime offline',
    realtimeRequestFailed: 'Realtime request failed. Using last successful snapshot.',
    realtimeRateLimited: 'API rate limited. Retrying…',
    realtimeNetworkError: 'Network issue. Check your connection.',
    stationRequestFailed: 'Station arrivals request failed.',
    stationRateLimited: 'Station request rate limited. Retrying…',
    startupRequestFailed: 'Initial data request failed.',
    refreshingData: 'Refreshing data...',
    dataRefreshed: 'Data refreshed',
    manualRefresh: 'Refresh data',

    hotspotTitle: 'Station Hotspots',
    hotspotNotableDelays: (count) => `${count} station${count === 1 ? '' : 's'} with notable delays`,
    hotspotAllNormal: 'All stations within normal range',
    hotspotAvgDelay: (min) => `Avg ${min} min late`,
    hotspotWorstDelay: (min) => `worst ${min} min`,
    hotspotDetailTitle: (label) => `Station Detail — ${label}`,
    hotspotDetailSubtitle: (count, vehicleLabel, avgMin) => `${count} ${vehicleLabel} · avg ${avgMin} min late`,
    hotspotNoVehicles: 'No vehicle data at this station',
    hotspotDelayText: (min) => `${min} min late`,

    // Direction base labels
    northboundLabel: 'Northbound',
    southboundLabel: 'Southbound',
    directionTo: (base, dest) => `${base} to ${dest}`,
    etcLabel: 'etc.',

    // Timeline / Service window
    midnightStartLabel: '12:00 AM',
    midnightEndLabel: '12:00 AM',
    todayServiceWindowTitle: 'Today Service Window',
    serviceOverflowNote: (label) => `Covers today through midnight, then continues to ${label}`,
    serviceFirstLastNote: 'First trip, last trip, and current time',
    inServiceBadge: 'In service',
    offHoursBadge: 'Off hours',
    currentTimeAria: 'Current time',

    // Vehicle location
    vehicleAt: (label) => `At ${label}`,
    vehicleCurrentlyAt: (label) => `Currently at ${label}`,
    vehicleRunningBetween: (from, to) => `Running from ${from} to ${to}`,

    // Train list
    nextUpKicker: 'Next up',
    followingVehiclesHeading: 'Following vehicles',
    betweenLabel: 'Between',
    lineDiagramAria: (name) => `${name} live LED board`,
    usingLastSnapshot: 'Using last successful snapshot',

    // Attention reasons
    reasonLargeGap: 'Large gap',
    reasonSevereLate: 'Severe late',
    reasonAlerted: 'Alerted',
    reasonImbalanced: 'Imbalanced',
    reasonHealthy: 'Healthy',

    // Headway / spacing
    tooFewForSpacing: (label) => `Too few ${label} for a spacing read`,
    observedGapRange: (min, max) => `${min}-${max} min observed gap`,
    balanceBalanced: 'Balanced',
    balanceNorthHeavier: 'Northbound heavier',
    balanceSouthHeavier: 'Southbound heavier',

    // Delay distribution chips
    delayOnTimeChip: 'On time',
    delayMinorChip: '2-5 min late',
    delaySevereChip: '5+ min late',

    // Line exceptions
    serviceHole: (dir, min) => `${dir} has a ${min} min service hole right now.`,
    vehicleTilt: (dir, count) => `Vehicle distribution is tilted toward ${dir} by ${count}.`,
    vehiclesRunningLate: (count, label) => `${count} ${label} are running 5+ min late.`,
    alertsAffecting: (name, count) => `${count} active alert${count === 1 ? '' : 's'} affecting ${name}.`,
    spacingStable: 'Spacing and punctuality look stable right now.',

    // System summary - top issue
    noMajorIssues: 'No major active issues right now.',
    topIssueAlerts: (name, count) => `${name} has ${count} active alert${count === 1 ? '' : 's'}.`,
    topIssueGap: (name, gap) => `Largest live gap: ${gap} min on ${name}.`,
    topIssueLate: (name, count, label) => `${name} has ${count} ${label} running 5+ min late.`,

    // Metric deltas
    flatVsSnapshot: 'Flat vs last snapshot',
    metricImproving: 'Improving',
    metricWorse: 'Worse',

    // System summary - exceptions
    alertsAcrossLines: (alerts, lines) => `${alerts} active alert${alerts === 1 ? '' : 's'} across ${lines} line${lines === 1 ? '' : 's'}.`,
    linesWithLateVehicles: (count) => `${count} line${count === 1 ? '' : 's'} have vehicles running 5+ min late.`,
    linesUnevenSpacing: (count) => `${count} line${count === 1 ? '' : 's'} show uneven spacing right now.`,
    systemStable: 'System looks stable right now with no major active issues.',

    // System summary - labels
    onTimeRateLabel: 'On-Time Rate',
    attentionLinesLabel: 'Attention Lines',
    summaryTitle: 'Summary',
    systemLinesUpdated: (count, time) => `${count} line${count === 1 ? '' : 's'} in system · Updated ${time}`,
    healthyLinesLabel: 'Healthy Lines',
    liveVehiclesLabel: (label) => `Live ${label}`,
    alertsChipLabel: 'Alerts',
    linesNeedingAttention: 'Lines Needing Attention',
    impactedStopsChipLabel: 'Impacted Stops',
    attentionBreakdown: 'Attention Breakdown',
    attentionBreakdownNote: 'Split by lateness and spacing issues',
    lateOnlyLabel: 'Late Only',
    spacingOnlyLabel: 'Spacing Only',
    bothIssuesChipLabel: 'Both',
    recommendedNext: 'Recommended Next',
    recommendedNextNote: 'Best next checks from the current snapshot',
    gapMinSummary: (gap) => `Gap ${gap} min`,
    noMajorSpacingIssue: 'No major spacing issue',
    severeLateCountText: (count) => `${count} severe late`,
    alertCountText: (count) => `${count} alert${count === 1 ? '' : 's'}`,
    attentionRanking: 'Attention Ranking',
    realtimeDegraded: 'Realtime degraded, using last successful snapshot',
    fromLiveSnapshot: 'Derived from the current live snapshot only',
    scoreSummary: (score) => `Score ${score}`,
    systemStatusTitle: 'System Status',

    // Insights ticker
    insightsSummaryAria: 'Current insights summary',
    noActiveIssues: 'No active issues right now.',

    // Line insights
    inServiceLabel: 'In Service',
    worstGapLabel: 'Worst Gap',
    balanceChipLabel: 'Balance',
    directionFlow: (dir) => `${dir} flow`,
    lineAlertsNote: (count, stops) => `${count} active alert${count === 1 ? '' : 's'}${stops ? ` · ${stops} impacted stops` : ''}`,
    noAlertsOnLine: 'No active alerts on this line',
    waitingForLiveData: (label) => `Waiting for live ${label} data…`,

    // Insights detail panels
    vehicleWord: 'Vehicle',
    earlyLabel: 'Early',
    delayMinutesText: (min) => `${min} min late`,
    northboundShort: 'Northbound',
    southboundShort: 'Southbound',
    noGapDataFor: (dir) => `No gap data for ${dir}`,
    detailInServiceTitle: (name) => `In Service — ${name}`,
    vehiclesTotal: (count) => `${count} vehicles total`,
    noVehicleData: 'No vehicle data',
    detailOnTimeTitle: (name) => `On-Time Rate — ${name}`,
    detailSpacingTitle: (name) => `Spacing — ${name}`,
    worstGapSubtitle: (gap) => `Worst gap: ${gap} min`,
    noGapData: 'No gap data',
    detailBalanceTitle: (name) => `Direction Balance — ${name}`,
    directionVehicleCounts: (nbLabel, nbCount, sbLabel, sbCount) => `${nbLabel}: ${nbCount} · ${sbLabel}: ${sbCount}`,
    vehicleCountUnit: (count) => `${count} vehicle${count !== 1 ? 's' : ''}`,
    detailHeadwayTitle: (dir, name) => `${dir} Spacing — ${name}`,
    averageMinutes: (avg) => `Average: ${avg} min`,
    tooFewVehiclesForSpacing: 'Too few vehicles for a spacing read',
    delayOnTimeTitle: 'On Time',
    delayMinorTitle: '2-5 Min Late',
    delaySevereTitle: '5+ Min Late',
    noVehiclesInCategory: 'No vehicles in this category',
    detailAttentionTitle: (name) => `Attention Score — ${name}`,
    scoreSubtitle: (score) => `Score: ${score}`,
    scoreChipLabel: 'Score',
    severeLateChipLabel: 'Severe Late',
    activeAlertsChipLabel: 'Active Alerts',
    reasonChipLabel: 'Reason',

    // System detail panels
    healthyLinesSubtitle: (count) => `${count} line${count !== 1 ? 's' : ''} running smoothly`,
    vehiclesInServiceText: (count) => `${count} in service`,
    spacingPunctualityNormal: 'Spacing and punctuality normal',
    noHealthyLines: 'No fully healthy lines right now',
    vehiclesSystemTotal: (count) => `${count} total`,
    nbSbCountsText: (nb, sb) => `NB: ${nb} · SB: ${sb}`,
    alertsDetailSubtitle: (count, lines) => `${count} alerts across ${lines} line${lines !== 1 ? 's' : ''}`,
    activeAlertCountText: (count) => `${count} active alert${count !== 1 ? 's' : ''}`,
    noActiveAlertsNow: 'No active alerts right now',
    attentionLinesSubtitle: (count) => `${count} line${count !== 1 ? 's' : ''}`,
    unevenSpacingText: 'Uneven spacing',
    noAttentionLines: 'No lines needing attention right now',
    impactedStopsTitle: 'Impacted Stops',
    stopsAffected: (count) => `${count} stop${count !== 1 ? 's' : ''} affected`,
    noImpactedStops: 'No impacted stops right now',
    lateOnlyLinesTitle: 'Late Only Lines',
    severelyLateVehicles: (count) => `${count} severely late vehicle${count !== 1 ? 's' : ''}`,
    noLateOnlyLines: 'No late-only lines right now',
    spacingOnlyLinesTitle: 'Spacing Only Lines',
    noSpacingOnlyLines: 'No spacing-only lines right now',
    bothIssuesTitle: 'Both Issues',
    bothIssuesSummary: (gap, count) => `Gap ${gap} min · ${count} severely late`,
    noBothIssueLines: 'No lines with both issues right now',
    lineCountText: (count) => `${count} line${count !== 1 ? 's' : ''}`,

    // Ride mode
    rideModeActivated: (name) => `Riding to ${name}`,
    rideModeHeadsUp: (name, stops) => `${name} is ${stops} stop${stops === 1 ? '' : 's'} away`,
    rideModeArrival: (name) => `Next stop: ${name} — get ready!`,
    rideModeDeactivated: 'Ride mode ended',
    rideModeChip: (name, stops) => `${name} · ${stops} stop${stops === 1 ? '' : 's'}`,
    rideModeCancel: 'Cancel ride alert',
    rideModeLost: 'Lost track of your vehicle. Ride mode ended.',
    rideModeDirectionChanged: 'Vehicle changed direction. Ride mode ended.',
    rideModeNotifyButton: 'Alert me here',
    rideModeBanner: (name, stops) => `Riding to ${name} — ${stops} stop${stops === 1 ? '' : 's'} away`,
    rideModeAlreadySet: (name) => `Already tracking to ${name}`,
    rideModeNotifyPermission: 'Enable notifications to get alerted at your stop.',
  },
  'zh-CN': {
    languageToggle: 'EN',
    languageToggleAria: '切换到英文',
    themeLight: '浅色',
    themeDark: '深色',
    themeToggleAria: '切换主题',
    transitSystems: '交通系统',
    boardViews: '视图切换',
    openStationSearch: '站点搜索',
    openAbout: '关于',

    stationSearchPlaceholder: '搜索站点、线路或系统',
    stationSearchHint: '可直接跳转到任意已加载系统中的站点。',
    useMyLocation: '使用我的位置',
    locationFindingButton: '定位中…',
    locationFinding: '正在获取你的位置…',
    locationFoundNearby: (count) => `显示最近的 ${count} 个站点`,
    locationNoNearby: '在已加载数据中未找到附近站点。',
    locationPermissionDenied: '定位权限被拒绝。',
    locationUnavailable: '当前位置暂时不可用。',
    locationTimedOut: '定位请求超时。',
    locationFailed: '无法获取当前位置。',
    locationUnsupported: '当前浏览器不支持定位。',
    nearbyStationsHint: '点击"使用我的位置"即可查找最近站点。',
    nearbyStationsFound: (count) => `${count} 个附近站点`,
    nearbyStationBadge: '附近',
    realtimeBadge: '实时',
    scheduleBadge: '计划',
    searchShortcut: '按 / 键搜索',
    searchKeyboardHint: '↑↓ 导航 · Enter 选择',
    recentSearches: '最近',
    recentlyViewed: '最近查看',
    noStationSearchResults: '没有匹配的站点。',
    stationSearchResults: (count) => `找到 ${count} 个站点`,
    tabMap: '地图',
    tabFavorites: '收藏',
    tabInsights: '洞察',
    statusSync: '同步',
    statusHold: '暂停',
    statusFail: '失败',
    waitingSnapshot: '等待快照',
    updatedNow: '刚刚更新',
    updatedSecondsAgo: (seconds) => `${seconds} 秒前更新`,
    updatedMinutesAgo: (minutes) => `${minutes} 分钟前更新`,
    station: '站点',
    serviceSummary: '服务摘要',
    boardDirectionView: '到站屏方向视图',
    both: '双向',
    directionUp: '上行',
    directionDown: '下行',
    board: '到站屏',
    exit: '退出',
    northbound: '北向 (▲)',
    southbound: '南向 (▼)',
    train: '列车',
    currentMovement: '当前位置',
    closeTrainDialog: '关闭列车详情',
    serviceAlert: '服务通知',
    transitAdvisory: '交通提示',
    closeAlertDialog: '关闭通知详情',
    readOfficialAlert: '查看官方公告',
    aboutTitle: '关于 Link Pulse',
    aboutSummary: '隐私、支持与版本信息',
    closeAboutDialog: '关闭关于弹窗',
    aboutProductTitle: '应用',
    aboutProductBody: (version) => `Link Pulse ${version} 是一个面向 Link、RapidRide 与 Swift 的移动实时看板。`,
    aboutPrivacyTitle: '隐私',
    aboutPrivacyBody: '只有在你主动使用“附近站点”功能时才会请求定位。收藏站点、最近浏览、主题和语言偏好都保存在你的设备本地，应用不需要账号登录。',
    aboutPrivacyLink: '查看隐私政策',
    aboutSupportTitle: '支持',
    aboutSupportBody: '问题反馈、Bug 报告和建议可以通过项目支持页面提交。',
    aboutSupportLink: '获取支持',
    aboutSourceTitle: '项目',
    aboutSourceBody: (bundleId) => `Bundle ID：${bundleId}`,
    aboutSourceLink: '查看源码',
    shareArrivals: '分享',
    shareArrivalsAria: '分享到站时间',
    shareSuccess: '已分享到站信息！',
    shareCopied: '到站信息已复制到剪贴板',
    shareFailed: '无法分享到站信息',
    addFavorite: '添加到收藏',
    removeFavorite: '从收藏移除',
    moveUp: '上移',
    moveDown: '下移',
    favoriteAdded: '已添加到收藏',
    favoriteRemoved: '已从收藏移除',
    noFavorites: '暂无收藏站点。',
    favoritesHint: '收藏常用站点，方便快速访问。',
    favoritesTitle: '收藏站点',
    favoritesLiveHint: '收藏卡片现在会直接显示双向最近到站。',
    favoritesArrivalsLoading: '正在加载实时到站…',
    favoritesArrivalsUnavailable: '实时到站暂时不可用。',
    favoritesStationMissing: '该站点已不在当前静态数据中。',
    favoritesNoUpcoming: (label) => `未来 1 小时内暂无${label}`,
    arriving: '即将到站',
    todayServiceUnavailable: '今日运营时间不可用',
    todayServiceSpan: (start, end) => `今日 ${start} - ${end}`,
    lastTrip: (time) => `末班 ${time}`,
    endsIn: (duration) => `${duration} 后结束`,
    firstTrip: (time) => `首班 ${time}`,
    startsIn: (duration) => `${duration} 后开始`,
    serviceEnded: (time) => `已于 ${time} 收班`,
    nextStart: (time) => `下次首班 ${time}`,
    noNextServiceLoaded: '暂无下次运营数据',
    ended: '已结束',
    nextFirstTrip: (time) => `下次首班 ${time}`,
    noServiceRemainingToday: '今日班次已结束',
    serviceHoursUnavailable: '运营时间不可用',
    staticScheduleMissing: '当前日期缺少静态时刻表数据',
    unavailable: '不可用',
    serviceSummaryUnavailable: '暂无服务摘要',
    alertsWord: () => '通知',
    scheduled: '按时刻表',
    onTime: '准点',
    unknown: '未知',
    lateMinutes: (min) => `晚点 ${min} 分钟`,
    earlyMinutes: (min) => `早到 ${min} 分钟`,
    onTimeStatus: '准点',
    arrivalMinSec: (m, s) => `${m}分 ${s}秒`,
    arrivalSec: (s) => `${s}秒`,
    durationHoursMinutes: (h, m) => `${h}小时${m}分钟`,
    durationHours: (h) => `${h}小时`,
    durationMinutes: (m) => `${m}分钟`,
    nextDaySuffix: (offset) => `（次日${offset > 1 ? `+${offset - 1}` : ''}）`,
    arrivingStatus: '即将到站',
    delayedStatus: '晚点',
    enRoute: '运行中',
    arrivingNow: '正在进站',
    arrivingIn: (time) => `${time} 后到站`,
    nextStopIn: (time) => `${time} 后到下一站`,
    active: '运营中',
    noLiveVehicles: (label) => `暂无实时${label}`,
    liveCount: (count, label) => `${count} 辆实时${label}`,
    inServiceCount: (count, label) => `${count} 辆${label}运营中`,
    activeVehicles: (label) => `${label}列表`,
    previous: '上一站',
    now: '当前',
    next: '下一站',
    direction: '方向',
    terminal: '终点',
    etaToTerminal: '到终点 ETA',
    upcomingStops: '后续站点',
    liveEtaNow: '实时 ETA',
    currentLocation: '当前位置',
    nextStop: '下一站',
    progress: '进度',
    lineProgress: (pct) => `${pct}%`,
    directionAll: '全部',
    filterByDirection: '按方向筛选',
    headwayGap: (min) => `间隔 ${min} 分钟`,
    headwayGapLabel: (min) => `${min} 分`,
    upcoming: '后续',
    noDownstreamEta: '当前暂无这趟列车后续站点 ETA。',
    terminalFallback: '终点',
    loadingArrivals: '正在加载到站信息...',
    noUpcomingVehicles: (label) => `暂无即将到站的${label}`,
    noAdditionalVehicles: (label) => `暂无更多${label}`,
    stopAway: (count) => `还有 ${count} 站`,
    toDestination: (name) => `开往 ${name}`,
    activeAlerts: (count) => `${count} 条当前通知`,
    noActiveAlerts: '暂无当前通知。',
    noAdditionalAlertDetails: '暂无更多详情。',
    affectedLineAlerts: (lineName) => `${lineName} 通知`,
    realtimeOffline: '实时数据离线',
    realtimeRequestFailed: '实时请求失败，正在使用最近一次成功快照。',
    realtimeRateLimited: 'API 频率受限，正在重试…',
    realtimeNetworkError: '网络异常，请检查连接。',
    stationRequestFailed: '获取到站信息失败。',
    stationRateLimited: '站点请求频率受限，正在重试…',
    startupRequestFailed: '初始数据请求失败。',
    refreshingData: '正在刷新数据...',
    dataRefreshed: '数据已刷新',
    manualRefresh: '刷新数据',

    hotspotTitle: '延误热点',
    hotspotNotableDelays: (count) => `${count} 个站点延误较高`,
    hotspotAllNormal: '各站点延误在正常范围',
    hotspotAvgDelay: (min) => `平均晚点 ${min} 分钟`,
    hotspotWorstDelay: (min) => `最差 ${min} 分钟`,
    hotspotDetailTitle: (label) => `站点详情 — ${label}`,
    hotspotDetailSubtitle: (count, vehicleLabel, avgMin) => `共 ${count} 辆 · 平均晚点 ${avgMin} 分钟`,
    hotspotNoVehicles: '该站点暂无车辆数据',
    hotspotDelayText: (min) => `晚点 ${min} 分钟`,

    // Direction base labels
    northboundLabel: '北向',
    southboundLabel: '南向',
    directionTo: (base, dest) => `${base} · 开往 ${dest}`,
    etcLabel: '等',

    // Timeline / Service window
    midnightStartLabel: '00:00',
    midnightEndLabel: '24:00',
    todayServiceWindowTitle: '今日运营时间带',
    serviceOverflowNote: (label) => `今日覆盖到午夜，继续运营至 ${label}`,
    serviceFirstLastNote: '首末班与当前时刻',
    inServiceBadge: '运营中',
    offHoursBadge: '未运营',
    currentTimeAria: '当前时间',

    // Vehicle location
    vehicleAt: (label) => `位于 ${label}`,
    vehicleCurrentlyAt: (label) => `当前位于 ${label}`,
    vehicleRunningBetween: (from, to) => `正从 ${from} 开往 ${to}`,

    // Train list
    nextUpKicker: '最近一班',
    followingVehiclesHeading: '后续车次',
    betweenLabel: '区间',
    lineDiagramAria: (name) => `${name} 实时线路图`,
    usingLastSnapshot: '使用最近一次成功快照',

    // Attention reasons
    reasonLargeGap: '大间隔',
    reasonSevereLate: '严重晚点',
    reasonAlerted: '有告警',
    reasonImbalanced: '方向失衡',
    reasonHealthy: '健康',

    // Headway / spacing
    tooFewForSpacing: (label) => `${label}数量不足，无法判断间隔`,
    observedGapRange: (min, max) => `观测间隔 ${min}-${max} 分钟`,
    balanceBalanced: '均衡',
    balanceNorthHeavier: '北向偏多',
    balanceSouthHeavier: '南向偏多',

    // Delay distribution chips
    delayOnTimeChip: '准点',
    delayMinorChip: '晚点 2-5 分钟',
    delaySevereChip: '晚点 5+ 分钟',

    // Line exceptions
    serviceHole: (dir, min) => `${dir} 当前有 ${min} 分钟的服务空档。`,
    vehicleTilt: (dir, count) => `车辆分布向 ${dir} 偏多 ${count} 辆。`,
    vehiclesRunningLate: (count, label) => `${count} 辆${label}晚点超过 5 分钟。`,
    alertsAffecting: (name, count) => `${name} 当前受 ${count} 条告警影响。`,
    spacingStable: '当前间隔和准点性都比较稳定。',

    // System summary - top issue
    noMajorIssues: '当前没有明显的主要问题。',
    topIssueAlerts: (name, count) => `${name} 当前有 ${count} 条生效告警。`,
    topIssueGap: (name, gap) => `${name} 当前最大实时间隔为 ${gap} 分钟。`,
    topIssueLate: (name, count, label) => `${name} 有 ${count} 辆${label}晚点超过 5 分钟。`,

    // Metric deltas
    flatVsSnapshot: '与上次快照持平',
    metricImproving: '改善',
    metricWorse: '变差',

    // System summary - exceptions
    alertsAcrossLines: (alerts, lines) => `${lines} 条线路共受 ${alerts} 条告警影响。`,
    linesWithLateVehicles: (count) => `${count} 条线路上有车辆晚点超过 5 分钟。`,
    linesUnevenSpacing: (count) => `${count} 条线路当前发车间隔不均。`,
    systemStable: '系统整体稳定，当前没有明显问题。',

    // System summary - labels
    onTimeRateLabel: '准点率',
    attentionLinesLabel: '需关注线路',
    summaryTitle: '概览',
    systemLinesUpdated: (count, time) => `系统内 ${count} 条线路 · 更新于 ${time}`,
    healthyLinesLabel: '健康线路',
    liveVehiclesLabel: (label) => `实时${label}`,
    alertsChipLabel: '告警',
    linesNeedingAttention: '需关注线路',
    impactedStopsChipLabel: '影响站点',
    attentionBreakdown: '需关注线路构成',
    attentionBreakdownNote: '按晚点与间隔异常拆解',
    lateOnlyLabel: '仅晚点',
    spacingOnlyLabel: '仅间隔不均',
    bothIssuesChipLabel: '两者都有',
    recommendedNext: '建议关注',
    recommendedNextNote: '基于当前快照的综合优先级',
    gapMinSummary: (gap) => `最大间隔 ${gap} 分钟`,
    noMajorSpacingIssue: '当前无明显间隔问题',
    severeLateCountText: (count) => `${count} 辆严重晚点`,
    alertCountText: (count) => `${count} 条告警`,
    attentionRanking: '关注排名',
    realtimeDegraded: '实时数据退化，使用最近一次成功快照',
    fromLiveSnapshot: '仅基于当前实时快照',
    scoreSummary: (score) => `评分 ${score}`,
    systemStatusTitle: '系统状态',

    // Insights ticker
    insightsSummaryAria: '当前洞察摘要',
    noActiveIssues: '当前没有活跃问题。',

    // Line insights
    inServiceLabel: '运营中',
    worstGapLabel: '最大间隔',
    balanceChipLabel: '方向平衡',
    directionFlow: (dir) => `${dir} 流向`,
    lineAlertsNote: (count, stops) => `${count} 条生效告警${stops ? ` · 影响 ${stops} 个站点` : ''}`,
    noAlertsOnLine: '本线路当前没有生效告警',
    waitingForLiveData: (label) => `等待实时${label}数据…`,

    // Insights detail panels
    vehicleWord: '车辆',
    earlyLabel: '早点',
    delayMinutesText: (min) => `晚点 ${min} 分钟`,
    northboundShort: '北行',
    southboundShort: '南行',
    noGapDataFor: (dir) => `${dir} 暂无间隔数据`,
    detailInServiceTitle: (name) => `运营中 — ${name}`,
    vehiclesTotal: (count) => `共 ${count} 辆`,
    noVehicleData: '暂无车辆数据',
    detailOnTimeTitle: (name) => `准点率 — ${name}`,
    detailSpacingTitle: (name) => `间隔详情 — ${name}`,
    worstGapSubtitle: (gap) => `最大间隔 ${gap} 分钟`,
    noGapData: '暂无间隔数据',
    detailBalanceTitle: (name) => `方向平衡 — ${name}`,
    directionVehicleCounts: (nbLabel, nbCount, sbLabel, sbCount) => `${nbLabel} ${nbCount} · ${sbLabel} ${sbCount}`,
    vehicleCountUnit: (count) => `${count} 辆`,
    detailHeadwayTitle: (dir, name) => `${dir} 间隔 — ${name}`,
    averageMinutes: (avg) => `平均 ${avg} 分钟`,
    tooFewVehiclesForSpacing: '车辆不足，无法计算间隔',
    delayOnTimeTitle: '准点',
    delayMinorTitle: '晚点 2-5 分钟',
    delaySevereTitle: '晚点 5+ 分钟',
    noVehiclesInCategory: '本分类暂无车辆',
    detailAttentionTitle: (name) => `关注评分 — ${name}`,
    scoreSubtitle: (score) => `综合评分 ${score}`,
    scoreChipLabel: '综合评分',
    severeLateChipLabel: '严重晚点',
    activeAlertsChipLabel: '活跃告警',
    reasonChipLabel: '关注原因',

    // System detail panels
    healthyLinesSubtitle: (count) => `${count} 条线路运行稳定`,
    vehiclesInServiceText: (count) => `${count} 辆运营中`,
    spacingPunctualityNormal: '间隔和准点性均正常',
    noHealthyLines: '当前没有完全健康的线路',
    vehiclesSystemTotal: (count) => `全系统共 ${count} 辆`,
    nbSbCountsText: (nb, sb) => `北行 ${nb} · 南行 ${sb}`,
    alertsDetailSubtitle: (count, lines) => `${count} 条告警影响 ${lines} 条线路`,
    activeAlertCountText: (count) => `${count} 条活跃告警`,
    noActiveAlertsNow: '当前没有活跃告警',
    attentionLinesSubtitle: (count) => `${count} 条线路`,
    unevenSpacingText: '间隔不均',
    noAttentionLines: '当前没有需关注的线路',
    impactedStopsTitle: '受影响站点',
    stopsAffected: (count) => `${count} 个站点受告警影响`,
    noImpactedStops: '当前没有受影响的站点',
    lateOnlyLinesTitle: '仅晚点线路',
    severelyLateVehicles: (count) => `${count} 辆严重晚点`,
    noLateOnlyLines: '当前没有仅晚点的线路',
    spacingOnlyLinesTitle: '仅间隔不均线路',
    noSpacingOnlyLines: '当前没有仅间隔不均的线路',
    bothIssuesTitle: '晚点且间隔不均',
    bothIssuesSummary: (gap, count) => `最大间隔 ${gap} 分钟 · ${count} 辆严重晚点`,
    noBothIssueLines: '当前没有两者都有问题的线路',
    lineCountText: (count) => `${count} 条线路`,

    // Ride mode
    rideModeActivated: (name) => `正在前往 ${name}`,
    rideModeHeadsUp: (name, stops) => `距离 ${name} 还有 ${stops} 站`,
    rideModeArrival: (name) => `下一站: ${name} — 准备下车！`,
    rideModeDeactivated: '乘车模式已结束',
    rideModeChip: (name, stops) => `${name} · ${stops} 站`,
    rideModeCancel: '取消到站提醒',
    rideModeLost: '无法追踪你的车辆，乘车模式已结束。',
    rideModeDirectionChanged: '车辆改变了方向，乘车模式已结束。',
    rideModeNotifyButton: '到站提醒',
    rideModeBanner: (name, stops) => `前往 ${name} — 还有 ${stops} 站`,
    rideModeAlreadySet: (name) => `正在追踪到 ${name}`,
    rideModeNotifyPermission: '开启通知以在到站时提醒你。',
  },
}
